apiVersion: v1
kind: Service
metadata:
  name: logstash
spec:
  ports:
    - name: http-gelf
      port: 12201
      targetPort: 12201
      protocol: UDP
    - name: http-beats
      port: 5000
      targetPort: 5000
      protocol: TCP
    - name: http-requests
      port: 9600
      targetPort: 9600
      protocol: TCP
  selector:
    app: logstash
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
        - name: logstash
          image: docker.elastic.co/logstash/logstash-oss:7.10.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 12201
              protocol: UDP
            - containerPort: 5000
              protocol: TCP
            - containerPort: 9600
              protocol: TCP
          resources:
            requests:
              memory: 700M
            limits:
              memory: 700M
          volumeMounts:
          - name: logstash-config
            mountPath: /usr/share/logstash/pipeline/gelf.conf
            subPath: gelf.conf
      volumes:
      - name: logstash-config
        configMap:
          name: logstash-cm
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: logstash-cm
data:
  gelf.conf: |
    input {
      gelf {
        port => 12201
      }
    }
    output {
      stdout {}
      elasticsearch {
        hosts => ["http://elasticsearch:9200"]
      }
    }